version: '3.7'

services:

  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A applikacia worker -l info -E --concurrency=1
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis
  redis:
    image: redis:alpine
  dashboard:
    build: .
    command:  celery -A applikacia flower
    volumes:
      - .:/usr/src/app    
    ports:
      - 5555:5555
    depends_on:
      - django
      - redis
      - celery
